/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as BibleRouteImport } from './routes/bible'
import { Route as DeskRouteImport } from './routes/desk'
import { Route as JvRouteImport } from './routes/jv'
import { Route as MoatRouteImport } from './routes/moat'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const BibleRoute = BibleRouteImport.update({
  id: '/bible',
  path: '/bible',
  getParentRoute: () => rootRouteImport,
} as any)
const DeskRoute = DeskRouteImport.update({
  id: '/desk',
  path: '/desk',
  getParentRoute: () => rootRouteImport,
} as any)
const JvRoute = JvRouteImport.update({
  id: '/jv',
  path: '/jv',
  getParentRoute: () => rootRouteImport,
} as any)
const MoatRoute = MoatRouteImport.update({
  id: '/moat',
  path: '/moat',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/bible': typeof BibleRoute
  '/desk': typeof DeskRoute
  '/jv': typeof JvRoute
  '/moat': typeof MoatRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/bible': typeof BibleRoute
  '/desk': typeof DeskRoute
  '/jv': typeof JvRoute
  '/moat': typeof MoatRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/bible': typeof BibleRoute
  '/desk': typeof DeskRoute
  '/jv': typeof JvRoute
  '/moat': typeof MoatRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/bible' | '/desk' | '/jv' | '/moat'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/bible' | '/desk' | '/jv' | '/moat'
  id: '__root__' | '/' | '/bible' | '/desk' | '/jv' | '/moat'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  BibleRoute: typeof BibleRoute
  DeskRoute: typeof DeskRoute
  JvRoute: typeof JvRoute
  MoatRoute: typeof MoatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bible': {
      id: '/bible'
      path: '/bible'
      fullPath: '/bible'
      preLoaderRoute: typeof BibleRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/desk': {
      id: '/desk'
      path: '/desk'
      fullPath: '/desk'
      preLoaderRoute: typeof DeskRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/jv': {
      id: '/jv'
      path: '/jv'
      fullPath: '/jv'
      preLoaderRoute: typeof JvRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/moat': {
      id: '/moat'
      path: '/moat'
      fullPath: '/moat'
      preLoaderRoute: typeof MoatRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  BibleRoute: BibleRoute,
  DeskRoute: DeskRoute,
  JvRoute: JvRoute,
  MoatRoute: MoatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
